sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t pvaz/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true pvaz/docker-react npm run test -- --coverage